### ISSUE TITLE
Crashes from Crafting while having storage ui opened

### ISSUE THREAD

**Issue by CelestialDawn** [thmsndk/Raft-CraftFromAllStorage#1]
There's no screenshots to provide because it hangs up and automatically closes the client. -- Might have any problems with other mods that are installed but there's that.

**Feel free to close this if needed.

**Comment by thmsndk** [comment]
Hi @CelestialDawn 

Thanks for reporting the issue, without a more solid reproduce I can't really do much though. 
Does it happen with only Craft From All Storage?
What version are you using?
Could  you describe what you where doing when it crashed.
What mods do you have installed?

**Comment by CelestialDawn** [comment]
- I think so, it doesn't crash when it's not loaded.
- Raft latest version (13.01) // All mods are updated too.
- I was hovering around the inventory + storage open and sometimes, crafting items and then it suddenly hangs up and closes the client.

- The mods that I was using are: Autorecipe (Redux), Benevolent Sprites, Better Steering Wheel, Craft From All Storage, ExtraSettings API, GarbageSucker + fix, Minimap, Model Electricity, MoreStorages, Scattered Remains, Solar Panel, and Stack Mod.

**Comment by thmsndk** [comment]
I did have it crash on me when I was developing it, but I figured it was because I was messing around with things. Next time it happens. could you check if the player log for your last session contains anything interesting, It should be located here `%AppData%\..\LocalLow\Redbeet Interactive\Raft\Player.log`

Raft by default does trigger some of the events I've hooked A LOT, And when thoose events trigger it searches all storages.
You mod list seems a lot like mine, except for a few ones.
How many storages do you have on your raft? And how full are they?

**Comment by CelestialDawn** [comment]
I will just put the player.log here because I don't have any clue where to look at. haha 
[Player.log](https://github.com/thmsndk/Raft-CraftFromAllStorage/files/6834104/Player.log)

But yeah, there's 2-3 small storages full because I'm still planning where to use them and tried hovering around while those are open and crashed :sweat_smile:

**Comment by Mathissoo** [comment]
https://youtu.be/vatLqNhRdZs there is video of this problem i tested it with other mods and with only CFAS and result is the same crash after hovering on items to craft while storage is open

**Comment by thmsndk** [comment]
@CelestialDawn I could not see anything out of the ordinary in your log file, the last thing that was logged seemed to be saving.

@Mathissoo so according to you it appears to have something to do with hovering quick crafts? I can see that the craft button itself is disabled. And you have 0/6 scrap, could also be related to not having enough resources? Are you doing anything specific to make it crash, and can you do it every time you load up the save?

**Comment by Mathissoo** [comment]
@thmsndk No im not doing anything specific to make the game crash just hovering my mouse over required resources while storage is open, and yes i can do it everytime

**Comment by thmsndk** [comment]
@Mathissoo Okay, so based on that video you are hovering items that are disabled and as soon as you hover the item where you actually have enough resources, you crash?

When you hover an item, it checks to see if you are able to quick craft it, by pressing the little green + icon. And it would seem like it is when it tries to show you the quick craft icon for crafting rope, that you crash. 

How many palm leafs do you have on your raft?

I'll try and see if I can reproduce it soon, I don't have too much time on my hands this current week. so any debugging you can do to get it to reliably crash helps a lot.

- Does it only crash with the shark bait recipe? 
- Can you make it crash with other recipes?
- Does crashing always involve 1 or more missing ingredients in the main recipe?

**Comment by Mathissoo** [comment]
No it crashes no matter if items are disable or not 
I have 242 leafs on my raft. 
It crashes with i think all recipes only some items like fishes doesn't crash my game. 
No it doesn't need to involve missing ingredients to crash my game like i said before only some items don't crash my game 

Mods List: Extra Setting API, Inventory Before Hotbar, MetalToScrap, Minimap, Building Utilities, Stat Modifier, Statistic Mod, Tombstones

**Comment by MelidoB** [comment]
I am having the same issue.

*Mods I'm using

![image](https://user-images.githubusercontent.com/48568341/126910742-0867da85-e371-40c8-a715-ee67729e57c8.png)

**Comment by thmsndk** [comment]
@CelestialDawn @MelidoB 

Okay, this is what I currently have as a reliable way to make Raft crash to desktop when using quickcraft. can you confirm if this is what happens when you crash?

- You have a storage open while using quick craft crafting (green +)
![image](https://user-images.githubusercontent.com/9084377/127372508-13b07a51-1acd-46b9-8dfb-37e231ea2f1e.png)
- once you craft the last item, and it is supposed to remove the last item from your currently open storage it crashes. e.g in this screenshot as soon as I press the green + on the rope, the game crashes
![image](https://user-images.githubusercontent.com/9084377/127372893-22be8066-871f-4eb7-9680-6a5a2079bd2d.png)

@Mathissoo I have not yet been able to reproduce the issue you had where it crashes when you hover over an item. But it must somehow be related to the check where it is supposed to verify if the green quick craft icon should be shown as green or red

![image](https://user-images.githubusercontent.com/9084377/127372403-d3d7eb9a-7880-41b7-a6fc-3197e020333c.png)
